### ISSUE TITLE
FORMATO DE ALTA

### ISSUE THREAD

**Issue by AdolfoPortugal** [TELNOR-TELVISTA/PROJECTS#12]
Se solcita formato de Alta para que la OA generen PV.

![Image](https://user-images.githubusercontent.com/129910499/231504051-a7c5df57-28f4-49ba-94c4-a536266a1855.png)

**Comment by AdolfoPortugal** [comment]
Buen día Ericka, de tu apoyo mandando el formato de alta para continuar con el proceso. 

Saludos!

**Comment by AdolfoPortugal** [comment]
Buen día Ericka, lograste avanzar con el Formato de alta?

**Comment by ErickaAlba** [comment]
Se envia formato a Martha A

![Image](https://user-images.githubusercontent.com/129985196/233508834-73f0fb16-1e4a-472c-873a-d2694d062374.png)
