### ISSUE TITLE
MANDAR CONTRATOS A FIRMA DEL REP. LEGAL

### ISSUE THREAD

**Issue by AdolfoPortugal** [TELNOR-TELVISTA/PROJECTS#14]
Tere, de tu apoyo para mandar los contratos a firma del representante lega, coordinar con Jairo para un solo envió.

Anexo correo de ejemplo:

Buen día estimados:

                Esperando se encuentren de lo mejor. El presente es para proporcionar los Contratos y los pueda pasar a firma por su Representante Legal, estos deben tener las siguientes condiciones:

•	Imprimir 2 tantos en original
•	Imprimir en una sola cara de la hoja
•	La firma debe ser en tinta azul preferentemente
•	Firmar y/o rubricar todas y cada una de las hojas
•	No subrayar ni resaltar ningún texto
•	No engrapar, usar solo clips
•	Entregar en un solo sobre.

Una vez firmados, le solicito me haga el favor de enviarme un juego por este mismo medio para su validación, una vez validados, le pediré una agenda para que personal Telnor pase al sitio por los originales, se manda a Dirección Telnor para firma de nuestro Rep. Legal y posteriormente, se le hace llegar un Juego original para su empresa.

Agradezco su apoyo y atención al presente, cualquier duda, quedo a la orden.

Saludos!

**Comment by TeresaAcevedo** [comment]
Se verifica que el Régimen Capital no viene anotado en los Contratos (SA DE CV) por lo que se manda validar con Devy Ochoa, en espera de su confirmación para mandar a firmar por el Rep. Legal o corregir Contratos.

**Comment by AdolfoPortugal** [comment]
Devy confirma que no hay problema por mandarlos así, favor de estar atenta a la copia escaneada para mandar recolectar originales.



![Image](https://user-images.githubusercontent.com/129910499/232924910-5c817740-d38d-486c-aefe-818fb72d61db.png)

**Comment by TeresaAcevedo** [comment]
Se confirma que Jairo ya mando los Contratos a firmar por el cliente. En espera/
