### ISSUE TITLE
LLAMAR A CLIENTE 14/04/2023 PARA DIMENSIONAMIENTO

### ISSUE THREAD

**Issue by ErickaAlba** [TELNOR-TELVISTA/PROJECTS#27]
CLIENTE CON ENLACE DE OTRO PROVEEDOR, LLAMAR PARA CONOCER CARACTERISTICAS DE REQUERIMIENTO.
Se llamo, pendiente requisitos de enlace, se envía correo de seguimiento 13/04/2023

**Comment by ErickaAlba** [comment]
Samuel de tu apoyo con estatus sobre seguimiento

**Comment by SamuelCordovaA** [comment]
Hola Ericka, de acuerdo a lo comentado este caso lo estoy trabajando con Adilene.

Saludos. 


![Image](https://user-images.githubusercontent.com/129912282/233678524-958d3e77-66cc-4bf0-86e0-b5b3f97cbddf.png)

**Comment by AdolfoPortugal** [comment]
Buen día estimados, procedo a añadir al caso a @AdileneCabello  y emito baja del caso de @ErickaAlba .

Saludos
