### ISSUE TITLE
AGENDAR VIDEOLLAMADA CON CLIENTE PRESENTAR COTIZACION IDN 50 MBPS

### ISSUE THREAD

**Issue by AdolfoPortugal** [TELNOR-TELVISTA/PROJECTS#3]
Agendar video llamada con cliente para presentar la solución y los beneficios de obtenerla.

**Comment by TeresaAcevedo** [comment]
Trabajo en la Agenda, quedo pendiente.

**Comment by AdolfoPortugal** [comment]
Perfecto, quedo en espera de la fecha, saludos

**Comment by AdolfoPortugal** [comment]
Buen día Tere, ¿Como vamos con esto?

**Comment by TeresaAcevedo** [comment]
Buen día Adolfo, Jairo informa que habló con el cliente y dice q no es necesaria una video llamada, ya que dice no tener dudas. Jairo le pidió por correo los Legales y el cliente solo está por definir si va a requerir el IDN de 20 0 50 MB, por lo que estamos en espera de los Legales para podértelos compartir y se puedan generar los Contratos,

[Correo de Jairo - Solicitud de Legales.docx](https://github.com/TELNOR-TELVISTA/PROJECTS/files/11203857/Correo.de.Jairo.-.Solicitud.de.Legales.docx)

Saludos!

**Comment by AdolfoPortugal** [comment]
Confirmo de enterado.

Saludos!
