### ISSUE TITLE
SEGUIMIENTO CONTRATOS PARA FIRMA DE CLIENTE

### ISSUE THREAD

**Issue by SamuelCordovaA** [TELNOR-TELVISTA/PROJECTS#5]
Se envió correo de contratos a ejecutivo para seguimiento con cliente. 

![Image](https://user-images.githubusercontent.com/129912282/230433166-71fdb413-e60c-4662-8e58-9462ddaf154a.png)

**Comment by SamuelCordovaA** [comment]
Enlace IDN CO218203/000002
Enlace IDE TCF-2003-0004.

**Comment by AdolfoPortugal** [comment]
Buen día Ericka, ¿cuál es el STATUS de este caso? ¿Porque sigue en TO-DO?¿Puerdo apoyar en algo para que esto salga de este concepto?

**Comment by ErickaAlba** [comment]
se genero hace 5 dias sin embargo no habiamos recibido la capa para seguimiemto , Gracias!!

.

**Comment by SamuelCordovaA** [comment]
Se envió documentation e historial del caso a ejecutivo asignado en ME para su seguimiento.

**Comment by SamuelCordovaA** [comment]
Se cierra caso por resignación de cliente
![Image](https://user-images.githubusercontent.com/129912282/231564639-86b40aed-f41a-458d-892a-9297f870a5ad.png)
