### ISSUE TITLE
PREPARAR PROPUESTA PBX EN LA NUBE (CUAD)

### ISSUE THREAD

**Issue by AdolfoPortugal** [TELNOR-TELVISTA/PROJECTS#6]
CLIENTE REQUIERE PROPUESTA DE CUAD, PBX EN LA NUBE, CON LA FINALIDAD DE UNIFICAR LAS COMUNICACIONES DE SUS 4 EMPRESAS.

**Comment by AdolfoPortugal** [comment]
Buen día estimado, de tu apoyo iniciando la propuesta para presentar la próxima semana,  saludos

**Comment by SamuelCordovaA** [comment]
Se trabaja en la propuesta.

**Comment by AdolfoPortugal** [comment]
Buenos días estimado, ¿Como vamos con la propuesta? Te anexo información de interés sobre el cliente



![Image](https://user-images.githubusercontent.com/129910499/231223138-8703d519-cfd8-4af0-b789-9c43914182f1.png)




![Image](https://user-images.githubusercontent.com/129910499/231223007-42bdc505-95cd-4a8b-976f-f9f69409f997.png)

**Comment by SamuelCordovaA** [comment]
Que tal Adolfo, te compartí propuesta de Webex y Cuad Telmex, quedo atento a comentarios.

**Comment by AdolfoPortugal** [comment]
[IP CLOUD + WEBEX - SKILL CERTIFICATION SERVICES MODIFICADA.pdf](https://github.com/TELNOR-TELVISTA/PROJECTS/files/11203660/IP.CLOUD.%2B.WEBEX.-.SKILL.CERTIFICATION.SERVICES.MODIFICADA.pdf)



[IP CLOUD + WEBEX - SKILL CERTIFICATION SERVICES.pdf](https://github.com/TELNOR-TELVISTA/PROJECTS/files/11203661/IP.CLOUD.%2B.WEBEX.-.SKILL.CERTIFICATION.SERVICES.pdf)



[CUAD TELMEX - SKILL CERTIFICATION SERVICES.pdf](https://github.com/TELNOR-TELVISTA/PROJECTS/files/11203662/CUAD.TELMEX.-.SKILL.CERTIFICATION.SERVICES.pdf)
