### ISSUE TITLE
AGENDAR VIDEO LLAMADA PARA PRESENTAR SOLUCION

### ISSUE THREAD

**Issue by AdileneCabello** [TELNOR-TELVISTA/PROJECTS#8]
AGENDA CON CLIENTE PIZZA FELIZ 

CLIENTE

ALBERTO

664222352

**Comment by AdolfoPortugal** [comment]
EN ESPERA DE AGENDA, QUEDO PENDIENTE

**Comment by AdileneCabello** [comment]
LE LLAMARE A CLIENTE EL DIA LUNES PARA REALIZAR CITA

**Comment by AdileneCabello** [comment]
SE AGENDO VIDEO EL DIA MARTES 12 DE ABRIL

**Comment by AdileneCabello** [comment]
SE AGENDO VIDEO EL DIA MARTES 12 DE ABRIL
